spring:
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  datasource:
    url: jdbc:h2:mem:tonycho
    driverClassName: org.h2.Driver
    username: sa
    password: 1111
  h2:
    console:
      enabled: true
  sql:
    init:
      mode: always
#      schema-locations: classpath:sql/schema-project.sql
#      data-locations: classpath:sql/data-project.sql