spring:
  jpa:
    hibernate:
      ddl-auto: create
  datasource:
    url: jdbc:h2:mem:tonycho
    driverClassName: org.h2.Driver
    username: sa
    password: 1111
  h2:
    console:
      enabled: true
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

app:
  description: Spring Boot Course Tracker API
  version: V1

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true